trigger:
- main

pool:
  name: TerraformTraining

variables:
  workingDir: '$(Build.SourcesDirectory)\Client-XYZ'
  serviceConnection: 'TerraformTraining'
  terraformVersion: '1.5.7'

stages:


- stage: Plan
  displayName: Terraform Plan
  jobs:
  - job: PlanJob
    steps:
    - checkout: self

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: '$(terraformVersion)'


    - script: terraform -version
      displayName: Verify Terraform Version

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskv4@4
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(workingDir)'
        backendServiceArm: '$(serviceConnection)'
        backendAzureRmResourceGroupName: 'tf-rg'
        backendAzureRmStorageAccountName: 'tfstorageacct123'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'terraform.tfstate'

    - script: terraform validate
      workingDirectory: $(workingDir)
      displayName: Terraform Validate


    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskv4@4
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(workingDir)'
        environmentServiceNameAzureRM: '$(serviceConnection)'
        commandOptions: '-out=tfplan'

   
    - publish: $(workingDir)\tfplan
      artifact: tfplan



- stage: Apply
  displayName: Terraform Apply
  dependsOn: Plan
  condition: succeeded()

  jobs:
  - deployment: ApplyJob
    displayName: Apply with Approval
    environment: prod-approval   

    strategy:
      runOnce:
        deploy:
          steps:

          - checkout: self

          - download: current
            artifact: tfplan

          
          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
            displayName: Install Terraform
            inputs:
              terraformVersion: '$(terraformVersion)'

          - script: terraform -version
            displayName: Verify Terraform Version


          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskv4@4
            displayName: Terraform Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(workingDir)'
              backendServiceArm: '$(serviceConnection)'
              backendAzureRmResourceGroupName: 'tf-rg'
              backendAzureRmStorageAccountName: 'tfstorageacct123'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'terraform.tfstate'

     
          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskv4@4
            displayName: Terraform Apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(workingDir)'
              environmentServiceNameAzureRM: '$(serviceConnection)'
              commandOptions: 'tfplan'